# Use a imagem oficial do PostgreSQL como base
FROM postgres:15

# Defina variáveis de ambiente para configuração do banco de dados
ENV POSTGRES_USER=docker
ENV POSTGRES_PASSWORD=password
ENV POSTGRES_DB=sistema-estoque2

# Copie scripts SQL ou outros arquivos necessários para inicialização
# COPY init.sql /docker-entrypoint-initdb.d/

# Exponha a porta padrão do PostgreSQL
EXPOSE 5432




