services:
  - type: web
    name: backend
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    rootDir: backend
    envVars:
      - key: DATABASE_URL
        value: sua_string_de_conexao
